# -*- coding: utf-8 -*-
"""sentence similarity

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1En8LU3XXaz6ea3phgvZEmE52YeJXF4ob
"""

!pip  install transformers touch

from sentence_transformers import SentenceTransformer,util

#Load the model
model = SentenceTransformer('all-MiniLM-L6-v2')

#Take input from user
text1=input("Enter the first text:")
text2=input("Enter the second text:")

#convert text to embeddings
embedding1=model.encode(text1)
embedding2=model.encode(text2)

#calculate similarity
similarity=util.cos_sim(embedding1,embedding2)

#show result
print("\nsimlarity Score:",round(float(similarity),2))

if similarity > 0.75:
    print("Similarity Level:High")
elif similarity > 0.4:
  print("Similarity Level:Medium")
else:
  print("Similarity Level:Low")